### ISSUE TITLE
RemoteEntry.json 404 not found

### ISSUE THREAD

**Issue by joepeace01** [angular-architects/module-federation-plugin#656] opened 2024-10-03 10:30 UTC
### For which library do you need help?

native-federation

### Question

Hi, I'm having issue implementing native federation since angular 17 and now on angular 18. I'm trying to connect my host app with a remote app on a different repository. It was working find on angular 16 with webpack and module federation but can't make it work with native federation. I've done all the configuration but when I'm running my app I'm getting a 404 not found on remoteEntry.json and when I check the endpoint used it's http://localhost:4200/remoteEntry.json (port of my host app) when it should be http://localhost:4201/remoteEntry.json (port of my remote app), and I don't understand why it's trying to fetch the file on port 4200.

Here are my files on the host app:
angular.json

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "maboussole": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-architects/native-federation:build",
          "options": {
          },
          "configurations": {
            "production": {
							"target": "maboussole:esbuild:production"
						},
            "preprod": {
							"target": "maboussole:esbuild:preprod"
						},
            "release": {
							"target": "maboussole:esbuild:release"
						},
						"development": {
							"target": "maboussole:esbuild:development",
							"dev": true
						}
          }
        },
        "esbuild": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "outputPath": "dist/maboussole/",
            "index": "src/index.html",
            "browser": "src/main.ts",
            "polyfills": [
							"zone.js",
							"es-module-shims",
              "@angular/localize/init"
						],
            "tsConfig": "tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/robots.txt",
              "src/sitemap-index.xml",
              "src/sitemap1.xml",
              "src/sitemap2.xml",
              "src/assets"
            ],
            "styles": [
              "node_modules/bootstrap/scss/bootstrap.scss"
            ],
            "stylePreprocessorOptions": {
              "includePaths": [
                "./SASS-Modules"
              ]
            },
            "server": "src/main.server.ts",
            "ssr": {
              "entry": "server.ts"
            },
            "allowedCommonJsDependencies": ["html2canvas", "canvg", "@angular-architects/native-federation", "compression", "moment", "jspdf"],
            "scripts": [],
            "extractLicenses": false,
            "sourceMap": true,
            "optimization": true
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractLicenses": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "20mb",
                  "maximumError": "20mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "200kb"
                }
              ]
            },
            "preprod": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.ppr.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractLicenses": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "20mb",
                  "maximumError": "20mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "200kb"
                }
              ]
            },
            "release": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.release.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractLicenses": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "20mb",
                  "maximumError": "20mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "200kb"
                }
              ]
            },
            "development": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractLicenses": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "20mb",
                  "maximumError": "20mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "200kb"
                }
              ]
            }
          },
          "defaultConfiguration": "development"
        },
        "serve": {
          "builder": "@angular-architects/native-federation:build",
          "options": {
            "target": "maboussole:serve-original:development",
            "rebuildDelay": 0,
            "dev": true,
            "port": 0
          }
        },
        "serve-original": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
						"port": 4200
					},
          "configurations": {
            "production": {
              "buildTarget": "maboussole:esbuild:production"
            },
            "preprod": {
              "buildTarget": "maboussole:esbuild:preprod"
            },
            "release": {
              "buildTarget": "maboussole:esbuild:release"
            },
            "development": {
              "buildTarget": "maboussole:esbuild:development"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "buildTarget": "maboussole:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": [
							"zone.js",
							"es-module-shims",
              "@angular/localize/init"
						],
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": ["src/favicon.ico", "src/assets"],
            "styles": ["node_modules/bootstrap/scss/bootstrap.scss"],
            "stylePreprocessorOptions": {
              "includePaths": ["./SASS-Modules"]
            },
            "scripts": []
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "maboussole:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "maboussole:serve:production"
            },
            "preprod": {
              "devServerTarget": "maboussole:serve:preprod"
            },
            "release": {
              "devServerTarget": "maboussole:serve:release"
            },
            "development": {
              "devServerTarget": "maboussole:serve:development"
            }
          }
        },
        "lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "lintFilePatterns": [
              "src/**/*.ts",
              "src/**/*.html"
            ]
          }
        }
      }
    }
  },
  "cli": {
    "schematicCollections": [
      "@angular-eslint/schematics"
    ],
    "analytics": false
  }
}
```

packge.json:

```
"dependencies": {
    "-": "^0.0.1",
    "@angular-architects/native-federation": "^18.2.2",
    "@angular-devkit/build-angular": "^18.2.7",
    "@angular/animations": "^18.2.7",
    "@angular/cdk": "^18.2.6",
    "@angular/common": "^18.2.7",
    "@angular/compiler": "^18.2.7",
    "@angular/core": "^18.2.7",
    "@angular/forms": "^18.2.7",
    "@angular/localize": "^18.2.7",
    "@angular/material": "^18.2.6",
    "@angular/platform-browser": "^18.2.7",
    "@angular/platform-browser-dynamic": "^18.2.7",
    "@angular/platform-server": "^18.2.7",
    "@angular/router": "^18.2.7",
    "@angular/service-worker": "^18.2.7",
    "@angular/ssr": "^18.2.7",
    "@compodoc/compodoc": "^1.1.25",
    "@fortawesome/angular-fontawesome": "^0.15.0",
    "@fortawesome/fontawesome-svg-core": "^6.6.0",
    "@fortawesome/free-brands-svg-icons": "^6.6.0",
    "@fortawesome/free-regular-svg-icons": "^6.6.0",
    "@fortawesome/free-solid-svg-icons": "^6.6.0",
    "@gfx/zopfli": "^1.0.15",
    "@ng-bootstrap/ng-bootstrap": "^17.0.1",
    "@popperjs/core": "^2.11.8",
    "@types/compression": "^1.7.4",
    "bootstrap": "^5.3.2",
    "brotli": "^1.3.3",
    "compress-brotli": "^1.3.12",
    "compression": "^1.7.4",
    "css-loader": "^7.1.2",
    "D": "^1.0.0",
    "es-module-shims": "^1.10.0",
    "express": "^4.19.2",
    "file-saver": "^2.0.5",
    "google-libphonenumber": "^3.2.38",
    "gzipper": "^8.1.0",
    "html2canvas": "^1.4.1",
    "http-server": "^14.1.1",
    "isbot": "^5.1.17",
    "jquery": "^3.7.1",
    "jspdf": "^2.5.1",
    "moment": "^2.30.1",
    "ng": "0.0.0",
    "ngx-bootstrap": "^18.0.2",
    "ngx-build-plus": "^18.0.0",
    "ngx-cookie-service": "^18.0.0",
    "postcss": "^8.4.31",
    "postcss-loader": "^8.1.1",
    "rxjs": "^7.8.1",
    "save": "^2.9.0",
    "serve": "^14.2.3",
    "style-loader": "^4.0.0",
    "tslib": "^2.6.2",
    "zone.js": "^0.14.4"
  },
  "devDependencies": {
    "@angular-eslint/builder": "^18.3.0",
    "@angular-eslint/eslint-plugin": "^18.3.0",
    "@angular-eslint/eslint-plugin-template": "^18.3.0",
    "@angular-eslint/schematics": "^18.3.0",
    "@angular-eslint/template-parser": "^18.3.0",
    "@angular-ru/prettier": "^14.0.13",
    "@angular/cli": "^18.2.7",
    "@angular/compiler-cli": "^18.2.7",
    "@angular/language-service": "^18.2.7",
    "@types/express": "^4.17.20",
    "@types/jasmine": "^5.1.1",
    "@types/jasminewd2": "^2.0.12",
    "@types/jspdf": "^2.0.0",
    "@types/moment": "^2.13.0",
    "@types/node": "^20.8.7",
    "@typescript-eslint/eslint-plugin": "^6.8.0",
    "@typescript-eslint/parser": "^6.8.0",
    "browser-sync": "^3.0.0",
    "compression-webpack-plugin": "^11.1.0",
    "copyfiles": "^2.4.1",
    "eslint": "^8.51.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.1",
    "husky": "^8.0.3",
    "jasmine-core": "^5.1.1",
    "jasmine-spec-reporter": "^7.0.0",
    "ng-packagr": "^18.2.1",
    "npm-run-all": "^4.1.5",
    "prettier": "^3.3.3",
    "pretty-quick": "^4.0.0",
    "rimraf": "^5.0.5",
    "ts-node": "^10.9.1",
    "typescript": "^5.5.4"
  },
  "overrides": {
    "vite": "^5.4.3"
  }
```

federation.config.js:

```
const { withNativeFederation, shareAll } = require('@angular-architects/native-federation/config');

module.exports = withNativeFederation({

  shared: {
    ...shareAll({ singleton: true, strictVersion: true, requiredVersion: 'auto' }),
  },

  skip: [
    'rxjs/ajax',
    'rxjs/fetch',
    'rxjs/testing',
    'rxjs/webSocket',
    // Add further packages you don't need at runtime
  ]
  
});
```

main.ts:

```
import { initFederation } from '@angular-architects/native-federation';
import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from 'app/app.component';
import { appConfig } from 'app/app.config';
import { environment } from '@environments/environment';

initFederation(`assets/manifests/${environment.remoteAccess.mfeEvenement}`)
  .catch((err) => console.error(err))
  .then((_) => bootstrapApplication(AppComponent, appConfig))
  .catch((err) => console.error(err));
```

manifest:

```
{
  "mfeEvenement": "http://localhost:4201/remoteEntry.json"
}
```

routing file:

```
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { EventPageComponent } from './event-page.component';
import { loadRemoteModule } from '@angular-architects/native-federation';

const routes: Routes = [
  {
    path: '',
    component: EventPageComponent,
    children: [
      {
        path: '',
        loadComponent: () => loadRemoteModule('mfeEvenement', './AppComponent').then((m) => m.AppComponent).catch((e) => console.log('REMOTE ERROR:', e)),
      },
    ],
  },
];
@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class EventPageRoutingModule {}
```

Remote app files:

angular.json:

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "mfe-evenement": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "mfe-evenement",
      "sourceRoot": "mfe-evenement/src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-architects/native-federation:build",
          "configurations": {
						"production": {
							"target": "remote:esbuild:production"
						},
            "qa": {
							"target": "remote:esbuild:qa"
						},
						"development": {
							"target": "remote:esbuild:development",
							"dev": true
						}
					}
        },
        "esbuild": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "outputPath": "dist/mfe-evenement/",
            "index": "mfe-evenement/src/index.html",
            "browser": "mfe-evenement/src/main.ts",
            "polyfills": ["mfe-evenement/src/polyfills.ts"],
            "tsConfig": "mfe-evenement/tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": ["mfe-evenement/src/favicon.ico", "mfe-evenement/src/assets/"],
            "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css"
            ],
            "stylePreprocessorOptions": {
              "includePaths": ["./SASS-Modules"]
            },
            "allowedCommonJsDependencies": [
              "html2canvas",
              "canvg",
              "@angular-architects/native-federation",
              "compression",
              "moment",
              "jspdf"
            ],
            "server": "mfe-evenement/src/main.server.ts",
            "ssr": {
              "entry": "mfe-evenement/server.ts"
            },
            "scripts": [],
            "extractLicenses": false,
            "sourceMap": true,
            "optimization": true
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "mfe-evenement/src/environments/environment.ts",
                  "with": "mfe-evenement/src/environments/environment.prod.ts"
                }
              ],
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "700kb",
                  "maximumError": "15mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "80kb",
                  "maximumError": "1mb"
                }
              ],
              "outputHashing": "all"
            },
            "qa": {
              "fileReplacements": [
                {
                  "replace": "mfe-evenement/src/environments/environment.ts",
                  "with": "mfe-evenement/src/environments/environment.qa.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractLicenses": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ]
            },
            "development": {
              "optimization": false,
              "extractLicenses": false,
              "sourceMap": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-architects/native-federation:build",
          "options": {
            "target": "mfe-evenement:serve-original:development",
            "rebuildDelay": 0,
            "dev": true,
            "port": 0
          }
        },
        "serve-original": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "buildTarget": "mfe-evenement:esbuild:production"
            },
            "qa": {
              "buildTarget": "mfe-evenement:esbuild:qa"
            },
            "development": {
              "buildTarget": "mfe-evenement:esbuild:development"
            }
          },
          "defaultConfiguration": "development",
          "options": {
            "port": 4201,
            "publicHost": "http://localhost:4201"
          }
        },
        "lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "lintFilePatterns": ["mfe-evenement/src/**/*.ts", "mfe-evenement/src/**/*.html"]
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "buildTarget": "mfe-evenement:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "polyfills": ["mfe-evenement/src/polyfills.ts"],
            "tsConfig": "mfe-evenement/tsconfig.spec.json",
            "inlineStyleLanguage": "scss",
            "assets": ["mfe-evenement/src/favicon.ico", "mfe-evenement/src/assets"],
            "styles": [
              "mfe-evenement/src/styles.scss",
              "node_modules/bootstrap/dist/css/bootstrap.css",
              "node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css"
            ],
            "scripts": []
          }
        }
      }
    }
  }
}
```

package.json:

```
"dependencies": {
    "@angular/animations": "^18.2.7",
    "@angular/cdk": "^18.2.6",
    "@angular/common": "^18.2.7",
    "@angular/compiler": "^18.2.7",
    "@angular/core": "^18.2.7",
    "@angular/forms": "^18.2.7",
    "@angular/material": "^18.2.6",
    "@angular/platform-browser": "^18.2.7",
    "@angular/platform-browser-dynamic": "^18.2.7",
    "@angular/platform-server": "^18.2.7",
    "@angular/router": "^18.2.7",
    "@angular/service-worker": "^18.2.7",
    "@angular/ssr": "^18.2.7",
    "@ng-bootstrap/ng-bootstrap": "^17.0.1",
    "@popperjs/core": "^2.11.8",
    "@types/compression": "^1.7.5",
    "bootstrap": "^5.3.3",
    "brotli": "^1.3.3",
    "calendar-link": "^2.7.0",
    "compress-brotli": "^1.3.12",
    "compression": "^1.7.4",
    "express": "^4.19.2",
    "gzipper": "^8.1.0",
    "isbot": "^5.1.17",
    "jspdf-html2canvas": "^1.5.2",
    "ngx-bootstrap": "^18.0.2",
    "ngx-cookie-service": "^18.0.0",
    "ngx-device-detector": "^8.0.0",
    "postcss": "^8.4.33",
    "rxjs": "^7.8.1",
    "tslib": "^2.6.2",
    "zone.js": "~0.14.10"
  },
  "devDependencies": {
    "@angular-architects/native-federation": "^18.2.2",
    "@angular-devkit/build-angular": "^18.2.7",
    "@angular-eslint/builder": "^18.3.0",
    "@angular-eslint/eslint-plugin": "^18.3.0",
    "@angular-eslint/eslint-plugin-template": "^18.3.0",
    "@angular-eslint/schematics": "^18.3.0",
    "@angular-eslint/template-parser": "^18.3.0",
    "@angular-ru/prettier": "^14.0.13",
    "@angular/cli": "^18.2.7",
    "@angular/compiler-cli": "^18.2.7",
    "@angular/localize": "^18.2.7",
    "@schematics/angular": "^18.2.7",
    "@types/express": "^4.17.21",
    "@types/jest": "^29.5.0",
    "@types/node": "^20.11.15",
    "@typescript-eslint/eslint-plugin": "^7.2.0",
    "@typescript-eslint/parser": "^7.2.0",
    "compression-webpack-plugin": "^11.1.0",
    "css-loader": "^6.8.1",
    "es-module-shims": "^1.10.0",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-angular": "^4.1.0",
    "eslint-plugin-prettier": "^5.1.3",
    "http-server": "^14.1.1",
    "ng-packagr": "^18.2.1",
    "ngx-build-plus": "^18.0.0",
    "prettier": "^3.2.4",
    "prettier-eslint": "^16.3.0",
    "sass": "^1.64.1",
    "thread-loader": "^3.0.4",
    "typescript": "^5.5.4"
  },
  "overrides": {
    "semver": "^7.5.3"
  }
```

federation.config.js:

```
const { withNativeFederation, shareAll } = require('@angular-architects/native-federation/config');

module.exports = withNativeFederation({
  name: 'mfeEvenement',

  exposes: {
    './AppComponent': 'mfe-evenement/src/app/app.component.ts',
  },

  shared: {
    ...shareAll({
      singleton: true,
      strictVersion: true,
      requiredVersion: 'auto',
    }),
  },
  skip: [
    'rxjs/ajax',
    'rxjs/fetch',
    'rxjs/testing',
    'rxjs/webSocket',
    // Add further packages you don't need at runtime
  ],
});

```

**Comment by rainerhahnekamp** [comment] 2024-10-03 10:35
@joepeace01 We are providing a stack blitz template for reproduction purposes. Would it be possible to provide us with an example?

**Comment by joepeace01** [comment] 2024-10-03 10:51
@rainerhahnekamp Is it possible to reproduce the fact that two app are on different repository and are communicarting remotly on stack blitz ?

**Comment by rainerhahnekamp** [comment] 2024-10-03 10:52
@joepeace01 yes. The link to the stackblitz is included in this issue's template: https://stackblitz.com/github/rainerhahnekamp/native-federation-stackblitz

**Comment by joepeace01** [comment] 2024-10-07 10:03
hi @rainerhahnekamp , so when I was trying to reproduce the issue on stackblitz I noticed that I made changes in my angular.json file because I had issue with the builder of native federation. I changed it back and now it seems that native federation is working on my remote app but on the host, when the app is builed, those files are generated instead of the regular ones, and when I lunch the app obviously he cannot find polyfills.js. And because of that the remoteEntry.json endpoint is never call

<img width="675" alt="Capture d’écran 2024-10-07 à 12 01 20" src="https://github.com/user-attachments/assets/da619405-0b83-4991-bbd7-e334a38b83dc">

**Comment by rainerhahnekamp** [comment] 2024-10-07 10:06
Can you provide us with a reproducible example that contains the same settings that you have locally?

**Comment by rainerhahnekamp** [comment] 2024-10-07 15:04
@joepeace01, native federation operates on entry points. fortawesome has multiple secondary ones, so you have to exclude all entry points from the library by using a regular expression:

<img width="457" alt="image" src="https://github.com/user-attachments/assets/43a6177f-6445-4954-bb6e-f93b6464ec7f">

Here's the link your corrected stackblit: https://stackblitz.com/edit/github-o8z75t-mjtlrb?file=projects%2Fremote%2Ffederation.config.js

I am going to close this issue, since it is resolved. If not, feel free to re-open it.

**Closed by rainerhahnekamp** 2024-10-07 15:04 UTC
Labels: project:native-federation, status:reproducible-stackblitz-requested
