### ISSUE TITLE
Issue with Angular Material

### ISSUE THREAD

**Issue by cnestor1** [angular-architects/module-federation-plugin#92] opened 2021-10-26 01:02 UTC
I built a quick prototype to test Angular material and MF using WebComponentWrapper based on this [tutorial](https://www.npmjs.com/package/@angular-architects/module-federation-tools).
The shell has 3 Angular material tabs. In the first tab, I display two remote micro frontends, (One React and one Angular).

- Once I render the app, the micro frontends render successfully in the first tab. 
- When I switch to the second tab, the static content renders. 
- When I switch back to the first tab, the React MF is there but the Angular MF is missing!

There is NO ERROR in the console. 

You can run the example here: (npm install - npm start)
Shell source code: [github](https://github.com/cnestor1/mf-material)

I followed this example for the Angular Microfrontend: https://github.com/manfredsteyer/angular-app1.
I used their Azure remote URL in the shell for the sake of brevity.

Is there something wrong with my config? Any help would be much appreciated!

My shell Webpack config is:
`  plugins: [
    new ModuleFederationPlugin({
      
          shared: share({
          "@angular/core": { singleton: true, strictVersion: true, requiredVersion: '12.2.11' },
          "@angular/common": { singleton: true, strictVersion: true, requiredVersion: '12.2.11' },
          "@angular/common/http": { singleton: true, strictVersion: true, requiredVersion: '12.2.11' },
          "@angular/router": { singleton: true, strictVersion: true, requiredVersion: '12.2.11' },
          "@angular/platform-browser": { singleton: true, strictVersion: true, requiredVersion: '12.2.11' },
          "@angular/platform-browser-dynamic": { singleton: true, strictVersion: true, requiredVersion: '12.2.11' },
          "@angular/animations": {singleton: true, eager: true},
          "rxjs": { singleton: true, strictVersion: true, requiredVersion: '6.6.7' },
          "rxjs/operators": { singleton: true, strictVersion: true, requiredVersion: '6.6.7' },

          ...sharedMappings.getDescriptors()
        })
        
    }),
    sharedMappings.getPlugin()
  ],
};`
 

The Angular remote (vanilla Angular 12 with MF plugin) :
` plugins: [
    new ModuleFederationPlugin({

      // For remotes (please adjust)
      name: "angular1",
      library: { type: "var", name: "angular1" },
      filename: "remoteEntry.js",
      exposes: {
        './web-components': './src/bootstrap.ts',
      },

      shared: {

        "@angular/core": { singleton: true},
        "@angular/common": { singleton: true },
        "@angular/common/http": { singleton: true },
        "@angular/router": { singleton: true },
        "@angular/platform-browser": { singleton: true },
        "@angular/platform-browser-dynamic": { singleton: true },
        "@angular/animations": {singleton: true, eager: true},
        "rx/js": { singleton: true, strictVersion: true, requiredVersion: '6.6.7' },
        "rxjs/operators": { singleton: true, strictVersion: true, requiredVersion: '6.6.7' },
      }
    }`

**Comment by vugar005** [comment] 2022-01-17 23:53
Hi , I see you have not included @angular/material in shared. Please see my solution thats works for me in https://github.com/angular-architects/module-federation-plugin/issues/113
Please let me know if it not works.

**Comment by mikezks** [comment] 2022-01-31 16:13
Please provide a repo to reproduce this.
The `rxjs` package name is not correct. Also, do only share real secondary entrypoints (with a package.json) and not normal subfolders like `rxjs/operators`.

**Comment by vugar005** [comment] 2022-01-31 16:47
I have an example working solution with material. You can check. https://github.com/vugar005/module-federation-space

**Comment by mikezks** [comment] 2022-01-31 17:24
Thanks @vugar005 - good to have this, also for supporting others in future.

We will close this issue soon, if the author has no follow-up comments on this.

**Closed** 2022-02-07 21:21 UTC
Labels: support request
